# Generated by Django 5.0 on 2023-12-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('back', '0002_delete_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='back',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
            ],
        ),
    ]
