# Generated by Django 5.0 on 2023-12-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='back',
        ),
    ]
